apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
      - name: first-job
        image: dmytrochnu/dockerjob
        command: ["python",  "manage.py", "migrate"]
      restartPolicy: Never
