# Generated by Django 3.1.7 on 2021-05-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('order collection', 'Order collection'), ('delivery', 'Delivery'), ('delivered', 'Delivered')], default='received', max_length=20),
        ),
    ]
