# Generated by Django 3.1.7 on 2021-05-11 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0001_initial'),
        ('orders', '0005_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='courier.courier'),
        ),
    ]
