# Generated by Django 3.1.7 on 2021-05-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210511_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shop',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
