# Generated by Django 3.1.7 on 2021-05-11 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='shop',
            new_name='shop_pr',
        ),
    ]
