# Generated by Django 3.1.7 on 2021-05-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210511_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='shop_pr',
            new_name='shop',
        ),
    ]
