# Generated by Django 3.1.7 on 2021-05-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210511_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shop',
        ),
    ]
