# Generated by Django 3.1.7 on 2021-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
