# Generated by Django 3.1.7 on 2021-05-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_reviews_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'default_related_name': 'products', 'ordering': ('-created',)},
        ),
    ]
