# Generated by Django 3.1.7 on 2021-05-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210516_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 - Very bad'), (2, '2 - Bad'), (3, '3 - Okay'), (4, '4 - Great'), (5, '5 - Excellent')]),
        ),
    ]
