# Generated by Django 3.1.7 on 2021-06-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210517_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image_products/no_img.png', upload_to='image_products/%Y/%m/%d'),
        ),
    ]
