# Generated by Django 3.1.7 on 2021-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=12)),
            ],
            options={
                'ordering': ('surname', 'name'),
                'default_related_name': 'courier',
            },
        ),
    ]
